// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVQT2y1kzbZObbOQ97gp7fzry8GcT9h0',
    appId: '1:245543280766:web:4e5eb6874de79856a7f82f',
    messagingSenderId: '245543280766',
    projectId: 'riderhub-abf78',
    authDomain: 'riderhub-abf78.firebaseapp.com',
    storageBucket: 'riderhub-abf78.firebasestorage.app',
    measurementId: 'G-5GV57QZ883',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlG4ney3gRPguaJbI8qccpsrlyMiJktFU',
    appId: '1:245543280766:android:a121f607b19e585da7f82f',
    messagingSenderId: '245543280766',
    projectId: 'riderhub-abf78',
    storageBucket: 'riderhub-abf78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRG78y2Ag20GTlveU_jZ77SSAE7B7Ur8',
    appId: '1:245543280766:ios:3127dce75c062ee7a7f82f',
    messagingSenderId: '245543280766',
    projectId: 'riderhub-abf78',
    storageBucket: 'riderhub-abf78.firebasestorage.app',
    iosClientId: '245543280766-ld1sc6217go48klof6nnimhh6ce0cao5.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcRG78y2Ag20GTlveU_jZ77SSAE7B7Ur8',
    appId: '1:245543280766:ios:3127dce75c062ee7a7f82f',
    messagingSenderId: '245543280766',
    projectId: 'riderhub-abf78',
    storageBucket: 'riderhub-abf78.firebasestorage.app',
    iosClientId: '245543280766-ld1sc6217go48klof6nnimhh6ce0cao5.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIVQT2y1kzbZObbOQ97gp7fzry8GcT9h0',
    appId: '1:245543280766:web:6407aad4a7282698a7f82f',
    messagingSenderId: '245543280766',
    projectId: 'riderhub-abf78',
    authDomain: 'riderhub-abf78.firebaseapp.com',
    storageBucket: 'riderhub-abf78.firebasestorage.app',
    measurementId: 'G-EEZ36MH9KN',
  );
}
